# Generated by Django 2.0.4 on 2018-05-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Lookup Table',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LookupTableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lookup_tables.LookupTable')),
            ],
            options={
                'verbose_name': 'Lookup Table Item',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='lookuptableitem',
            unique_together={('table', 'name')},
        ),
    ]
