# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('lookup_tables', '0001_initial'), ('lookup_tables', '0002_table_ref_field'), ('lookup_tables', '0003_auto_20180614_2034'), ('lookup_tables', '0004_auto_20180926_1753'), ('lookup_tables', '0005_auto_20180927_2134')]

    dependencies = [
    ]

    operations = [
    ]
