# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0003_auto_20180614_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookuptable',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lookuptableitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='lookuptable',
            name='default',
        ),
        migrations.RemoveField(
            model_name='lookuptable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lookuptable',
            name='table_ref',
        ),
        migrations.AlterUniqueTogether(
            name='lookuptableitem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lookuptableitem',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='lookuptableitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lookuptableitem',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='lookuptableitem',
            name='table',
        ),
    ]
