# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup_tables', '0004_auto_20180926_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LookupTable',
        ),
        migrations.DeleteModel(
            name='LookupTableItem',
        ),
    ]
