# Generated by Django 2.0.4 on 2018-06-15 18:51

from django.db import migrations, models
import django.db.models.deletion
import lookup_tables.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup_tables', '0002_table_ref_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', lookup_tables.fields.LookupTableItemField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', table_ref='mymodel-category', to='lookup_tables.LookupTableItem')),
                ('status', lookup_tables.fields.LookupTableItemField(on_delete=django.db.models.deletion.PROTECT, related_name='+', table_ref='mymodel-status', to='lookup_tables.LookupTableItem')),
                ('type', lookup_tables.fields.LookupTableItemField(on_delete=django.db.models.deletion.PROTECT, related_name='+', table_ref='mymodel-type', to='lookup_tables.LookupTableItem')),
            ],
        ),
    ]
