# Generated by Django 2.0.4 on 2018-06-15 18:51

from django.db import migrations, models
import django.db.models.deletion
import lookup_tables.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookup_tables', '0002_table_ref_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyModelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', lookup_tables.fields.LookupField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sample_app.MyModelCategory')),
                ('status', lookup_tables.fields.LookupField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sample_app.MyModelStatus')),
                ('type', lookup_tables.fields.LookupField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sample_app.MyModelType')),
            ],
        ),
    ]
